name: Build and Test C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cpp:
    name: Build and Test C++
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run C++ tests
      run: |
        cd build
        ctest --output-on-failure

  test-python:
    name: Run Python Unit Tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python + pytest
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install pytest

    - name: Run Python tests
      run: |
        pytest