name: Build and Test ROS2 env

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  ROS_CI:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        ros2_distribution:
          - humble
          - jazzy

        include: 
          # ROS 2 Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          # ROS 2 Jazzy Jalisco
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2
    
    container:
        image: ${{ matrix.docker_image }}
    
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Checkout code and setup workspace
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: |
            pkg_test