name: Build and Test C++

on:
  push:
    branches: [ main , humble , hub_action]
  pull_request:
    branches: [ main , humble, hub_action]

jobs:
  build-cpp:
    name: Build and Test C++
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run C++ tests
      run: |
        cd build
        ctest --output-on-failure

  # test-python:
  #   name: Run Python Unit Tests
  #   runs-on: ubuntu-22.04

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Install Python + pytest
  #     run: |
  #       sudo apt update
  #       sudo apt install -y python3-pip
  #       pip3 install pytest

  #   - name: Run Python tests
  #     run: |
  #       pytest
  test-ros2:
    name: ROS 2 Build & Test
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add ROS 2 GPG key and repo
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ros-archive-keyring.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update

    - name: Install ROS 2 Humble base packages
      run: |
        sudo apt install -y ros-humble-ros-base

    - name: Install colcon and dependencies
      run: |
        sudo apt install -y \
          python3-colcon-common-extensions \
          python3-pytest \
          python3-pytest-cov \
          python3-pip \
          ros-humble-rclpy \
          ros-humble-std-msgs
        pip3 install flake8

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --event-handlers console_direct+

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        colcon test 
    - name: Test result summary
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        colcon test-result --verbose
  
  
  ROS_CI:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        ros2_distribution:
          - humble
          - jazzy

        include: 
          # ROS 2 Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          # ROS 2 Jazzy Jalisco
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2
    
    container:
        image: ${{ matrix.docker_image }}
    
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Checkout code and setup workspace
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          package-name: |
            pkg_test    